RealEstate_Dapper_UI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using RealEstate_Dapper_UI.Dtos.CategoryDtos;
using RealEstate_Dapper_UI.Dtos.ProductDtos;
using RealEstate_Dapper_UI.Models;

namespace RealEstate_Dapper_UI.Controllers
{
    public class ProductController : Controller
    {
       private readonly IHttpClientFactory _httpClientFactory;
        private readonly ApiSettings _apisettings;
        public ProductController(IHttpClientFactory httpClientFactory, IOptions<ApiSettings> apisettings)
        {
            _httpClientFactory = httpClientFactory;
            _apisettings = apisettings.Value;
        }
        public async Task <IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var response = await client.GetAsync("Product/ProductListWithCategory");
            if (response.IsSuccessStatusCode)
            {
                var data =  await response.Content.ReadAsStringAsync();
                var listvalue = JsonConvert.DeserializeObject<List<ResultProductDtos>>(data);
                return View(listvalue);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateProduct()
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var response = await client.GetAsync("Category");

            var jsondata = await response.Content.ReadAsStringAsync();
            var categoryvalues = JsonConvert.DeserializeObject<List<ResultCategoryDto>>(jsondata);
            List<SelectListItem> selecteditem = (from x in categoryvalues.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.CategoryName,
                                                     Value = x.CategoryId.ToString()
                                                 }
                                               ).ToList();
            ViewBag.value=selecteditem;
            return View();
        }

        public async Task<IActionResult> DealOfTheDayStatusChangeToTrue(int id)
        {
            var client= _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var response = await client.GetAsync($"Product/DealOfTheDayStatusChangeToTrue/{id}");
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<IActionResult> DealOfTheDayStatusChangeToFalse(int id)
        {
           
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var response = await client.GetAsync($"Product/DealOfTheDayStatusChangeToFalse/{id}");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<ResultProductDtos>(data);
               
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

RealEstate_Dapper_UI/Controllers/PropertyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RealEstate_Dapper_UI.Dtos.ProductDetailDtos;
using RealEstate_Dapper_UI.Dtos.ProductDtos;
using RealEstate_Dapper_UI.Models;

namespace RealEstate_Dapper_UI.Controllers
{
    public class PropertyController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ApiSettings _apisettings;
        public PropertyController(IHttpClientFactory httpClientFactory,IOptions<ApiSettings> apisettings)
        {
            _httpClientFactory = httpClientFactory;
            _apisettings = apisettings.Value;
        }
        public async Task<IActionResult> Index()
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var responsemessage = await client.GetAsync("Product/ProductListWithCategory");
            if (responsemessage.IsSuccessStatusCode)
            {
                var JsonData = await responsemessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultProductDtos>>(JsonData);
                return View(values);
            }
            return View();
        }

        [HttpGet("property/{slug}/{id}")]
        public async Task<IActionResult>PropertySingle(string slug, int id)
        {
			ViewBag.ProductId = id;
            var sessionid = 0;
            HttpContext.Session.SetInt32("id", id);
            sessionid = (int)HttpContext.Session.GetInt32("id");

			var client = _httpClientFactory.CreateClient();
			var responseMessage = await client.GetAsync($"https://localhost:7093/api/Product/GetProductByProductId/{id}" );
			var jsonData = await responseMessage.Content.ReadAsStringAsync();
			var values = JsonConvert.DeserializeObject<ResultProductDtos>(jsonData);

			var client2 = _httpClientFactory.CreateClient();
			var responseMessage2 = await client2.GetAsync($"https://localhost:7093/api/ProductDetail/GetProductDetailByProduct/{sessionid}");
			var jsonData2 = await responseMessage2.Content.ReadAsStringAsync();
			var values2 = JsonConvert.DeserializeObject<GetByProductDetailIdDto>(jsonData2);

			ViewBag.ProductTitle = values.productTitle;
			ViewBag.ProductPrice = values.productPrice;
			ViewBag.City = values.city;
			ViewBag.District = values.district;
			ViewBag.Category = values.categoryName;
			ViewBag.img = values.ProductCoverImage;
			ViewBag.address = values.Address;
			ViewBag.Type = values.Type;
			ViewBag.Description = values.Description;

			ViewBag.BathRoomCount = values2.BathRoomCount;
			ViewBag.BedRoomCount = values2.BedRoomCount;
			ViewBag.roomCount = values2.RoomCount;
			ViewBag.garageSize = values2.GarageSize;
			ViewBag.buildYear = values2.BuildYear;
			ViewBag.price = values2.Price;
			ViewBag.location = values2.Location;
			ViewBag.videourl = values2.Videourl;
			ViewBag.size = values2.ProductSize;

			DateTime date = DateTime.Now;
			DateTime date2 = values.AdvertisementDate;
			TimeSpan timespan = date - date2;
			int month = timespan.Days / 30;
			ViewBag.month = month;
			ViewBag.date = values.AdvertisementDate;

			string slugFromTitle = CreateSlug(values.productTitle);
			ViewBag.slugUrl = slugFromTitle;

			return View();
		}

        public async Task<IActionResult> PropertyListWithSearch(string keyword, int categoryid, string city)
        {
            ViewBag.searchKeyValue = TempData["keyword"];
            ViewBag.propertyCategoryId = TempData["categoryid"];
            ViewBag.city = TempData["city"];

            keyword = TempData["keyword"].ToString();
            categoryid = int.Parse(TempData["categoryid"].ToString());
            city = TempData["city"].ToString();

            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var responseMessage = await client.GetAsync($"https://localhost:7093/api/Product/ResultProductWithSearchList?keyword={keyword}&categoryid={categoryid}&city={city}");
            if (responseMessage.IsSuccessStatusCode)
            {
                var jsonData = await responseMessage.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<List<ResultProductListWithSearchDto>>(jsonData);
                return View(values);
            }
            return View();
        }
        private string CreateSlug(string title)
        {
            title = title.ToLowerInvariant(); // Küçük harfe çevir
            title = title.Replace(" ", "-"); // Boşlukları tire ile değiştir
            title = System.Text.RegularExpressions.Regex.Replace(title, @"[^a-z0-9\s-]", ""); // Geçersiz karakterleri kaldır
            title = System.Text.RegularExpressions.Regex.Replace(title, @"\s+", " ").Trim(); // Birden fazla boşluğu tek boşluğa indir ve kenar boşluklarını kaldır
            title = System.Text.RegularExpressions.Regex.Replace(title, @"\s", "-"); // Boşlukları tire ile değiştir

            return title;
        }

        public async Task<IActionResult> PropertyDealsoftheDay()
        {
            var client=_httpClientFactory.CreateClient();
            client.BaseAddress = new Uri(_apisettings.BaseUrl);
            var response = await client.GetAsync("Product/GetProductByDealOfTheDayTrueWithCategory");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var json = JsonConvert.DeserializeObject<ResultProductDtos>(data);
                return View(json);
            }
            return View();
        }

    }
}

RealEstate_Dapper_UI/Views/Product/CreateProduct.cshtml
@* @using RealEstate_Dapper_UI.Dtos.ProductDtos
@model CreateProductDto
@{
    ViewData["Title"] = "CreateProduct";
    Layout = "~/Views/Admin/Index.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">

                <h6 class="mb-4">Yeni İlan Ekleme Sayfası</h6>
                <form method="post">
                    <label>İlan Başlığı</label>
                    <input type="text" asp-for="productTitle" class="form-control" />
                    <br />
                    <label>Şehir</label>
                    <input type="text" asp-for="city" class="form-control" />
                    <br />
                    <label>İlçe</label>
                    <input type="text" asp-for="district" class="form-control" />
                    <br />
                    <label>Kategori</label>
                    @Html.DropDownListFor(x => x.categoryid, (List<SelectListItem>)ViewBag.value, new { @class = "form-control" })
                    <label>Fiyat</label>
                    <input type="number" asp-for="produ" class="form-control" />
                    <br />
                    <label>Kapak Fotoğraf</label>
                    <input type="file" class="form-control" asp-for="ProductCoverImage" />
                    <br />
                    <label>İlan Açık Adres</label>
                    <input type="text" class="form-control" asp-for="Address" />
                    <br />
                    <button class="btn btn-primary" style="border-radius:8px">İlan Ekle</button>
                </form>
            </div>
        </div>
    </div>
    </div>
 *@

RealEstate_Dapper_UI/Views/Product/Index.cshtml
@model List<RealEstate_Dapper_UI.Dtos.ProductDtos.ResultProductDtos>
@{
    int count = 0;
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/Index.cshtml";
}

<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h3 class="mb-3" style="text-align:center">Ürün Tablosu</h3>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>

                                <th scope="col">Ürün İsmi</th>
                                <th scope="col">Ürünün Kategorisi</th>
                                <th scope="col">Ürünün Fiyatı</th>
                                <th scope="col">Sil</th>
                                <th scope="col">Güncelle</th>
                                <th scope="col">Sitede Gör</th>
                                <th scope="col">Günün Fırsatı</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var data in Model)
                            {
                                count++;
                                <tr>

                                    <td scope="row">@count</td>
                                    <td scope="row">@data.productTitle</td>
                                 <td scope="row">@data.categoryName</td>
                                 <td scope="row">@data.productPrice </td>

                                    <td scope="row"><a href="#" onclick="DeleteControl(@data.productId)" class="btn btn-outline-danger">Sil</a></td>
                                 <td>   <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModalCenter2">
                                        Güncelle
                                        </button>
                                    </td>
                                    <td scope="row">
                                        <a href="@Url.Action("PropertySingle","Property",new{slug=data.SlugUrl,id=data.productId})" class="btn btn-outline-info">
                                            Sitede gör
                                        </a>
                                    </td>
                                   
                                        @if (data.DealOfTheDay == false)
                                    {
                                        <td scope="row">
                                            <a href="/Product/DealOfTheDayStatusChangeToTrue/@data.productId" class="btn btn-outline-secondary">
                                               Fırsat Yap
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td scope="row">
                                            <a href="/Product/DealOfTheDayStatusChangeToFalse/@data.productId" class="btn btn-outline-danger">
                                                Fırsattan Çıkar
                                            </a>
                                        </td>
                                    }

                                   
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
                <a href="/Product/CreateProduct" class="btn btn-outline-info">
                    Yeni Ürün Girişi
                </a>

            

            </div>
        </div>
    </div>
</div>
<script>
    function DeleteControl(productid) {
        if (confirm("Silmek istiyor musunuz?")) {
            fetch(`https://localhost:7093/api/Product/${productid}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
                .then(response => {
                    if (response.ok) {
                        alert('Ürün başarıyla silindi');

                        location.reload();
                    } else {
                        alert('Bir hata oluştu. Lütfen tekrar deneyin.');
                    }
                })
                .catch(error => {
                    console.error('Hata:', error);
                    alert('Bir hata oluştu. Lütfen tekrar deneyin.');
                });
        }
    }
    </script>